### ISSUE TITLE
Add SECRET_KEY_BASE envvar

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/suri-rails#47]
Add this to the linked files in capistrano.

**Comment by ndushay** [comment]
> @cbeer said we should put that stuff in Environment variables set via puppet rather than in shared config

**Comment by ndushay** [comment]
puppet shows branches for shared_configs, but I don't believe those branches exist yet.

**Comment by jcoyne** [comment]
Tracking https://github.com/sul-dlss/operations-tasks/issues/2207

**Comment by mjgiarlo** [comment]
@jcoyne closed a few days ago. close this issue?
