### ISSUE TITLE
Add honeybadger

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/suri-rails#53]
Ensure that deployments are logged.

**Comment by ndushay** [comment]
> @cbeer said we should put that stuff in Environment variables set via puppet rather than in shared config

**Comment by ndushay** [comment]
puppet shows branches for shared_configs, but I don't believe those branches exist yet.

**Comment by justinlittman** [comment]
I think we should do it exactly the same as we do for every other project.

**Comment by jcoyne** [comment]
@justinlittman that is the direction we should be moving for every project and it is indeed what we do for some projects.

**Comment by mjgiarlo** [comment]
First things first: get the environment variables in place: https://github.com/sul-dlss/operations-tasks/issues/2211

I've self-assigned this ticket and will track this.
