### ISSUE TITLE
Update shared_configs to point to stage suri-rails

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/suri-rails#84]
Once the data has been migrated to the stage server, the following services will need to be updated (on stage) to point to the stage service:

- [x] argo-stage (suri not used directly)
- [x] dor-services-app-stage
- [x] hydrus-stage (suri not used directly)
- [x] sul-hydra-etd-stage
- [x] was-robots1-stage (suri not used directly)

**Comment by ndushay** [comment]
all of these already point to stage service.  so this is done.  If that's wrong ... whoops.
